server:
  servlet:
    contextPath: "/ws/api/v1/"

spring:
  data:
    mongodb:
      uri: mongodb://productListUser:productListPassword@localhost:27017/promotions?authSource=admin&retryWrites=true
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


#  application:
#    name: wallmart-test-back